config/routes.rb
Rails.application.routes.draw do

  get 'administrative', to: 'administrative#index'
  get 'dashboard', to: 'dashboard#index'
  
  namespace :administrative do
    resources :transfers, except: [:show]
    resources :events
    resources :projects
    resources :users
    post 'projects/:id/user_id=:user_id&act=:act', to: 'projects#edit_contributions'
    post 'events/:id/user_id=:user_id&act=:act', to: 'events#edit_participation'
  end
  
  namespace :dashboard do
    get 'transfers', to: "transfers#index"
    resources :events, only: [:index, :show]
    resources :projects, only: [:index, :show]
    resources :users, only: [:index, :show]
    resources :profile, only: [:edit, :update]
  end
  
  devise_for :admins , controllers: {sessions: 'sign/sessions'}
  devise_for :users,  controllers: {sessions: 'sign/sessions', registrations: 'sign/registrations' }
  
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :participations, dependent: :destroy
	has_many :users, through: :participations
	
	validates :name, :date, :description, presence: true
	
	scope :search, ->(term, page = 1) {
    where("lower(name) LIKE ?", "%#{term.downcase}%").order("LOWER(name)").page(page).per(6)
  }
end

app/controllers/administrative/events_controller.rb
class Administrative::EventsController < AdministrativeController
  before_action :set_event, only: [:edit,  :update, :destroy]
  
  def index
    query = ''
    if(params[:q])
      query = params[:q]
    end
   @events = Event.search(query, params[:page])
  end
  
  def new 
    @event = Event.new
  end 
  
  def show 
    @event = Event.find(params[:id])
    @event_users = @event.users
    
    query = ''
    if(params[:q])
      query = params[:q]
    end
    @users = User.search(query, params[:page])
  end

  def edit 
  end 

  def create 
    @event = Event.new(params_event)
    if @event.save
      redirect_to administrative_events_path, notice: "O evento #{@event.name} foi criado com sucesso"
    else
      render :new
    end
  end 

  def update
    if  @event.update(params_event)
       redirect_to administrative_events_path, notice: 
      "O evento #{@event.name} foi atualizado com sucesso"
    else 
      render :edit
    end
  end

  def destroy 
    if @event.present?
     # @event.users.clear #remove all associations
      @event.destroy
      redirect_to administrative_events_path, notice: "O evento #{@event.name} foi destruída com sucesso"
    else
      render :index
    end
  end
  
  def edit_participation
    event = Event.find(params[:id])
    user = User.find(params[:user_id])
    act = params[:act]
    p = event.participations.where("event_id=#{event.id} AND user_id=#{user.id}")
    if act == 'add'
      unless p.exists?
        if event.participations.create(user: user)
          redirect_to administrative_event_path(event.id), notice: "Participante Adicionado."
        else
          render :show
        end
      else
        redirect_to administrative_event_path(event.id), notice: "Participante já foi adicionado!"
      end
    elsif act == 'remove'
      if event.participations.delete(p)
        redirect_to administrative_event_path(event.id), notice: "Participante removido."
      else
        render :show
      end
    end
  end



  
private 

  def set_event 
    @event = Event.find(params[:id])
  end

  def params_event
     params.require(:event).permit(:name, :date, :description)
  end
end

app/controllers/administrative/projects_controller.rb
class Administrative::ProjectsController < AdministrativeController
  before_action :set_project, only: [:edit,  :update, :destroy, :show]
  
  def index
    query = ''
    if(params[:q])
      query = params[:q]
    end
    @projects = Project.search(query, params[:page]) 
  end
  
  def new 
    @project = Project.new
  end 

  def edit 
  end 

  def show
    @project_users = @project.users

    query = ''
    if(params[:q])
      query = params[:q]
    end
    @users = User.search(query, params[:page])

  end

  def create 
    @project = Project.new(params_project)
    if @project.save
      redirect_to administrative_projects_path, notice: "O projeto #{@project.name} foi criado com sucesso"
    else
      render :new
    end
  end 

  def edit_contributions
    project = Project.find(params[:id])
    user = User.find(params[:user_id])
    act = params[:act]
    p = project.contributions.where("project_id=#{project.id} AND user_id=#{user.id}")
    if act == 'add'
      unless p.exists?
        if project.contributions.create(user: user)
          redirect_to administrative_project_path(project.id), notice: "Membro adicionado com sucesso!"
        else
          render :show
        end
      else
        redirect_to administrative_project_path(project.id), notice: "Membro já foi adicionado!"
      end
    elsif act == 'remove'
      if project.contributions.delete(p)
        redirect_to administrative_project_path(project.id), notice: "Participante removido."
      else
        render :show
      end
    end
  end

  def update
    if  @project.update(params_project)
       redirect_to administrative_projects_path, notice: 
      "O projeto #{@project.name} foi atualizado com sucesso"
    else 
      render :edit
    end
  end

  def destroy 
    if @project.present?
    
      @project.destroy
      redirect_to administrative_projects_path, notice: "O projeto #{@project.name} foi destruído com sucesso"
    else
      render :index
    end
  end



  
private 

  def set_project 
    @project = Project.find(params[:id])
  end

  def params_project
     params.require(:project).permit(:name, :price,  :start_date, :description,  :client, :end_date, :expected_date)

  end
end

app/controllers/administrative/transfers_controller.rb
class Administrative::TransfersController < AdministrativeController
  before_action :set_transfer, only: [:edit, :update, :destroy]

  def index
    @transferences = Transfer.order(date: :desc).page(params[:page]).per(5)
  end 

  def new
      @transfer = Transfer.new
      @transfer.price = 0;
  end

  def create
    @transfer = Transfer.new(params_transfer)
    if @transfer.save
      redirect_to administrative_transfers_path, notice: "Criado"
    else
      render :new
    end
  end

  def edit
    # Uses the before_action to set the transfer.
  end

  def update
    if @transfer.update(params_transfer)
      redirect_to administrative_transfers_path, notice: "Atualizado"
    else
      render :edit
    end
  end

  def destroy
    if @transfer.destroy
      redirect_to  administrative_transfers_path, notice: "Excluído"
    else
      render :edit
    end
  end

  private

    def set_transfer
      @transfer = Transfer.find(params[:id])
    end

    def params_transfer
        params.require(:transfer).permit(:description, :price, :category, :date)
    end
  
end

app/controllers/administrative/users_controller.rb
class Administrative::UsersController < AdministrativeController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  def index
    query = ''
    if(params[:q])  
      query = params[:q]
    end
    @users = User.search(query, params[:page])
  end 
  
  def show 
    @user = User.find(params[:id])
    @user_projects = @user.projects
    @user_events = @user.events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params_user)
    if @user.save
      redirect_to administrative_users_path, notice: "Criado"
    else
      render :new
    end
  end

  def edit
    # Uses the before_action to set the user.
  end

  def update
    if @user.update(params_user)
      redirect_to administrative_users_path, notice: "Atualizado"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to  administrative_users_path, notice: "Excluído"
    else
      render :edit
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
    end

    def params_user
        params.require(:user).permit(:name,:email, :password, :password_confirmation,:birth_date,:address, :postal_code, :city, :gender, :phone, :photo, :role)
    end
end

app/controllers/administrative_controller.rb
class AdministrativeController < ApplicationController
  layout 'administrative'
  before_action :authenticate_admin!
  def index
    
    month = params[:month]
    if month.nil? or month == ''
      month = Date.today.to_s
    end
    @data = Date.parse(month)
    @dates = (@data.to_date..(@data + 1.month).to_date).map{ |date| date}
    @users = User.find_birth_dates_for( @data.to_date, (@data + 1.month).to_date)
    @events = Event.where(date: @data.to_date..(@data + 1.month).to_date ).order(:date)
    @projects_start = Project.where(start_date:  @data.to_date..(@data + 1.month).to_date ).order(:start_date)
    @projects_end = Project.where(end_date:  @data.to_date..(@data + 1.month).to_date ).order(:end_date)
    @projects_expected = Project.where(expected_date:  @data.to_date..(@data + 1.month).to_date ).order(:expected_date)
    
  end
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < DashboardController
  
  def index
  	query = ''
    if(params[:q])
      query = params[:q]
    end
    @events = Event.search(query, params[:page])
  end
  
  def show
    @event = Event.find(params[:id])
    @event_users = @event.users
  end 
end

app/helpers/administrative/events_helper.rb
module Administrative::EventsHelper
end

app/helpers/administrative/projects_helper.rb
module Administrative::ProjectsHelper
end

app/helpers/administrative/transfers_helper.rb
module Administrative::TransfersHelper
  OptionsForCategories = Struct.new(:id, :description)
  
  def options_for_categories
    options = []
    Transfer.categories_i18n.map do |key, value|
      options.push(OptionsForCategories.new(key,value))
    end
    options
  end
end

app/helpers/administrative/users_helper.rb
module Administrative::UsersHelper
end

app/helpers/administrative_helper.rb
module AdministrativeHelper
end

app/helpers/dashboard/events_helper.rb
module Dashboard::EventsHelper
end

app/views/administrative/events/edit.html.erb
<%= render partial: "administrative/events/shared/form",
           locals: {action_message: "Editando Evento "} %>

app/views/administrative/events/index.html.erb
<%= form_tag administrative_events_path, method: :get do %>
  <div class="box box-primary">
    <div class="box-header  with-border">
      <h3 class="box-title">Eventos</h3>
      <div class="box-tools">
        <div class="input-group input-group-sm" style="width: 150px;">
          <%= text_field_tag(:q, params[:q] , { class:"form-control pull-right", placeholder: "Pesquisar" }) %>
          <div class="input-group-btn">
            <%= button_tag(type: "submit", class: "btn btn-default") do %>
                <i class="fa fa-search"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="box-body table-responsive">
      <table class="table table-hover">
        <tbody>
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Description</th>
            <th></th>
          </tr>
          <% @events.each do |event| %>
            <tr>
              <td><%= event.name %></td>
              <td>
                <% if event.date? %>
                  <%= event.date.strftime("%d/%m/%Y") %>
                <% end %>
              </td>
              <td><%= event.description%></td>
              <td>
                <div class="btn-group-vertical">
                  <%= link_to administrative_event_path(event), class: "btn btn-sm btn-info" do %>
                    <i class="fa fa-eye"></i>
                  <% end %>
                  <%= link_to edit_administrative_event_path(event), class: "btn btn-sm btn-warning" do %>
                    <i class="fa fa-edit"></i>
                  <% end %>
                  <%= link_to administrative_event_path(event), method: :delete, data: { confirm: "Tem certeza que deseja excluir?" }, class: "btn btn-sm btn-danger" do %>
                    <i class="fa fa-trash"></i>
                  <% end %>
                </div>
              </td>
            </tr>
          <%end%>
        </tbody>
      </table>
      <hr>
      <%= paginate @events %>
      <div class="pull-right">
        <%= link_to new_administrative_event_path, class: "btn btn-success" do %>
          Novo <i class="fa fa-plus"></i>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/administrative/events/new.html.erb
<%= render partial: "administrative/events/shared/form",
           locals: {action_message: "Novo Evento "} %>

app/views/administrative/events/show.html.erb
<div class="row">
  <div class="col-md-8 col-sm-12">
    <%= render partial: "shared/show/event" %>
  </div>
  <div class="col-md-4 col-sm-12">
    <%= form_tag administrative_event_path(@event), method: :get do %>
      <div class="box box-default">
        <div class="box-header with-border">
          <h3 class="box-title">Adicionar Participantes</h3>
          <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
            </button>
          </div>
          <!-- /.box-tools -->
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <div class="input-group input-group-sm">
            <%= text_field_tag(:q, params[:q] , { class:"form-control pull-right", placeholder: "Pesquisar" }) %>
            <div class="input-group-btn">
              <%= button_tag(type: "submit", class: "btn btn-default") do %>
                  <i class="fa fa-search"></i>
              <% end %>
            </div>
          </div>
          <table class="table table-hover">
            <tbody>
              <tr>
                <th>Nome</th>
                <th>Cargo</th>
                <th></th>
              </tr>
              <% @users.each do |user| %>
                <tr>
                  <td> <%= user.name %> </td>
                  <td> <%= user.role %> </td>
                  <td>
                    <% unless @event.users.include? user %>
                      <%= link_to "/administrative/events/#{@event.id}/user_id=#{user.id}&act=add", method: :POST, class: "btn btn-sm btn-success" do %>
                        <i class="fa fa-plus"></i>
                      <% end %>
                    <% else %>
                      <%= link_to "/administrative/events/#{@event.id}/user_id=#{user.id}&act=remove", method: :POST, class: "btn btn-sm btn-danger" do %>
                        <i class="fa fa-minus"></i>
                      <% end %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @users %>
        </div>
        <!-- /.box-body -->
      </div>
    <% end %>
  </div>
</div>
 