config/routes.rb
Rails.application.routes.draw do

  get 'administrative', to: 'administrative#index'
  get 'dashboard', to: 'dashboard#index'
  
  namespace :administrative do
    resources :transfers, except: [:show]
    resources :events
    resources :projects
    resources :users
    post 'projects/:id/user_id=:user_id&act=:act', to: 'projects#edit_contributions'
    post 'events/:id/user_id=:user_id&act=:act', to: 'events#edit_participation'
  end
  
  namespace :dashboard do
    get 'transfers', to: "transfers#index"
    resources :events, only: [:index, :show]
    resources :projects, only: [:index, :show]
    resources :users, only: [:index, :show]
    resources :profile, only: [:edit, :update]
  end
  
  devise_for :admins , controllers: {sessions: 'sign/sessions'}
  devise_for :users,  controllers: {sessions: 'sign/sessions', registrations: 'sign/registrations' }
  
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :project, counter_cache: true
  belongs_to :user, counter_cache: true
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :participations, dependent: :destroy
	has_many :users, through: :participations
	
	validates :name, :date, :description, presence: true
	
	scope :search, ->(term, page = 1) {
    where("lower(name) LIKE ?", "%#{term.downcase}%").order("LOWER(name)").page(page).per(6)
  }
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :event , counter_cache: true
  belongs_to :user , counter_cache: true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :contributions, dependent: :destroy
	has_many :users, through: :contributions
	
	monetize :price_cents
	
	validates :name, :price_cents, :client, :start_date, presence: true

  scope :search, ->(term, page = 1) {
    where("lower(name) LIKE ?", "%#{term.downcase}%").order("LOWER(name)").page(page).per(6)
  }
end

app/models/projects_user.rb
class ProjectsUser < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/transfer.rb
class Transfer < ApplicationRecord
   # Constants
  CATEGORIES = {:out => 0, :in => 1}

  # Enums
  enum category: CATEGORIES
  
  validates :description, :category, :price_cents, :date, presence: true
  
  
  monetize :price_cents
end

app/models/user.rb
class User < ApplicationRecord

  has_many :contributions, dependent: :destroy
  has_many :projects, through: :contributions
  has_many :participations, dependent: :destroy
  has_many :events, through: :participations
  
  acts_as_birthday :birth_date
  
  mount_uploader :photo, AvatarUploader
  
  scope :search, ->(term, page = 1) {
    where("lower(name) LIKE ?", "%#{term.downcase}%").order("LOWER(name)").page(page).per(6)
  }

  validates :name, :email, :birth_date, :role, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

 # mount_uploader :photo, PhotoUploader       
end

app/controllers/administrative_controller.rb
class AdministrativeController < ApplicationController
  layout 'administrative'
  before_action :authenticate_admin!
  def index
    
    month = params[:month]
    if month.nil? or month == ''
      month = Date.today.to_s
    end
    @data = Date.parse(month)
    @dates = (@data.to_date..(@data + 1.month).to_date).map{ |date| date}
    @users = User.find_birth_dates_for( @data.to_date, (@data + 1.month).to_date)
    @events = Event.where(date: @data.to_date..(@data + 1.month).to_date ).order(:date)
    @projects_start = Project.where(start_date:  @data.to_date..(@data + 1.month).to_date ).order(:start_date)
    @projects_end = Project.where(end_date:  @data.to_date..(@data + 1.month).to_date ).order(:end_date)
    @projects_expected = Project.where(expected_date:  @data.to_date..(@data + 1.month).to_date ).order(:expected_date)
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  def index
    month = params[:month]
    if month.nil? or month == ''
      month = Date.today.to_s
    end
    @data = Date.parse(month)
    @dates = (@data.to_date..(@data + 1.month).to_date).map{ |date| date}
    @users = User.find_birth_dates_for( @data.to_date, (@data + 1.month).to_date)
    @events = Event.where(date: @data.to_date..(@data + 1.month).to_date ).order(:date)
    @projects_start = Project.where(start_date:  @data.to_date..(@data + 1.month).to_date ).order(:start_date)
    @projects_end = Project.where(end_date:  @data.to_date..(@data + 1.month).to_date ).order(:end_date)
    @projects_expected = Project.where(expected_date:  @data.to_date..(@data + 1.month).to_date ).order(:expected_date)
  end
end

app/controllers/sign/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/administrative_helper.rb
module AdministrativeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/events_helper.rb
module Dashboard::EventsHelper
end

app/helpers/dashboard/projects_helper.rb
module Dashboard::ProjectsHelper
end

app/helpers/dashboard/transfers_helper.rb
module Dashboard::TransfersHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/administrative_shared/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <%= link_to administrative_path, class:"logo" do %>
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>GTi</b>M</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>GTi</b> Members</span>
  <% end %>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
  </nav>
</header>

app/views/layouts/administrative_shared/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="/images/gti_admin_pic.png" class="img-circle" alt="User Image" />
      </div>
      <div class="pull-left info">
        <p><%= Admin.name %></p>
        <!-- Status -->
        <%= link_to destroy_admin_session_path, method: :delete do %>
          <i class="fa fa-sign-out text-danger"></i>Sair
        <% end %>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">CADASTROS</li>
      <li>
          <%= link_to administrative_events_path do %>
            <i class="fa fa-location-arrow"></i><span>Eventos</span>
          <% end %>
      </li>
      <li>
        <%= link_to administrative_projects_path do %>
          <i class="fa fa-archive"></i><span>Projetos</span>
        <% end %>
      </li>
      <li>
        <%= link_to administrative_users_path do %>
          <i class="fa fa-users"></i><span>Usuários</span>
        <% end %>
      </li>
      <li class="header">OUTROS</li>
      <li>

        <%= link_to administrative_transfers_path do %>

          <i class="fa fa-money"></i><span>Fluxo de Caixa</span>
        <% end %>
      </li> 
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>



      
      



      
      

app/views/layouts/shared/_admin_lte_2_header.html.erb
<!-- Main Header -->
<header class="main-header">

  <!-- Logo -->
  <%= link_to dashboard_path, class:"logo" do %>
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini"><b>GTi</b></span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg"><b>GTi</b>Members</span>
  <% end %>

  <!-- Header Navbar -->
  <nav class="navbar navbar-static-top" role="navigation">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
  </nav>
</header>

app/views/layouts/shared/_admin_lte_2_sidebar.html.erb
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">

  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">

    <!-- Sidebar user panel (optional) -->
    <div class="user-panel">
      <div class="pull-left image">
        <% if current_user.photo? %>
          <%= image_tag(current_user.photo.sidebar.url, :class => "img-circle") %>
        <% else %>
          <img src="/images/gti_user_pic.png" class="img-circle" alt="User Image" />
        <% end %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <!-- Status -->
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out text-danger"></i>Sair
        <% end %>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <ul class="sidebar-menu" data-widget="tree">
      <li class="header">INFORMAÇÕES</li>
      <li>
          <%= link_to administrative_events_path do %>
            <i class="fa fa-location-arrow"></i><span>Eventos</span>
          <% end %>
      </li>
      <li>
        <%= link_to administrative_projects_path do %>
          <i class="fa fa-archive"></i><span>Projetos</span>
        <% end %>
      </li>
      <li>
        <%= link_to administrative_users_path do %>
          <i class="fa fa-users"></i><span>Membros</span>
        <% end %>
      </li>
      <li>
        <%= link_to administrative_transfers_path do %>
          <i class="fa fa-money"></i><span>Fluxo de Caixa</span>
        <% end %>
      </li> 
      <li class="header">CONFIGURAÇÕES</li>
      <li>
        <%= link_to edit_dashboard_profile_path(current_user.id) do %>
          <i class="fa fa-user"></i><span>Meu Perfil</span>
        <% end %>
      </li> 
    </ul><!-- /.sidebar-menu -->
  </section>
  <!-- /.sidebar -->
</aside>



      
      



      
      

app/views/shared/_timeline.html.erb
<div class="box box-default">
  <div class="box-header with-border">
    <i class="fa fa-clock-o"></i>
    <h3 class="box-title">Timeline</h3>
  </div>
  <!-- /.box-header -->
  <div class="box-body">
    <% if controller_path.include? 'administrative' %>
      <% path = administrative_path %>
    <% elsif controller_path.include? 'dashboard' %>
      <% path = dashboard_path  %>
    <% end %>
    <%= form_tag path, class:"timeline-form", method: :get do %>
      <div class="input-group input-group-sm">
        <div class="input-group-btn">
          <%= button_tag(type: "button", class: "btn btn-default") do %>
              <i class="fa fa-calendar"></i>
          <% end %>
        </div>
        <%= text_field_tag(:month, params[:month] , { class:"form-control datepicker timeline-picker", placeholder: "Intervalo", autocomplete: "off" }) %>
      </div>
    <% end %>
  </div>
  <!-- /.box-body -->
</div>
<ul class="timeline">
    <!-- timeline time label -->
    <div class="box"> 
      <div class="box-body">
        <div class="row">
          <div class="col-md-6">
            <div class="description-block border-right">
              <h5 class="description-header"><i class="text-blue fa fa-calendar"></i> Início</h5>
              <span class="description-text"><%= @dates.first.strftime("%d/%m/%Y") %></span>
            </div>
          </div>
          <div class="col-md-6">
            <div class="description-block border-right">
              <h5 class="description-header"><i class="text-red fa fa-calendar"></i> Fim</h5>
              <span class="description-text"><%= @dates.last.strftime("%d/%m/%Y") %></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% @dates.each do |date| %>      
      <% @users.each do |user| %>
        <% if user.birth_date.month == date.month && user.birth_date.day == date.day %>
        <li class="time-label">
          <span class="bg-gray">
            <%= date.strftime("%d %b %y") %>
          </span>
        </li>
          <li>
            <i class="fa fa-birthday-cake bg-red"></i>
            <div class="timeline-item">
              <h3 class="timeline-header">Aniversário</h3>
              <div class="timeline-body"> 
                <span class="text-red"><%= user.name %></span> está completando <%= user.birth_date_age %> anos!
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
      <% @events.each do |event| %>
        <% if event.date.month == date.month && event.date.day == date.day %>
          <li class="time-label">
            <span class="bg-gray">
              <%= date.strftime("%d %b %y") %>
            </span>
          </li>
          <li>
            <i class="fa fa-location-arrow bg-yellow"></i>
            <div class="timeline-item">
              <h3 class="timeline-header">Evento</h3>
              <div class="timeline-body"> 
                <span class="text-yellow"><%= event.name %></span> acontecerá nesse dia!
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
      <% @projects_start.each do |project| %>
        <% if project.start_date.month == date.month && project.start_date.day == date.day %>
          <li class="time-label">
            <span class="bg-gray">
              <%= date.strftime("%d %b %y") %>
            </span>
          </li>
          <li>
            <i class="fa fa-bolt bg-light-blue"></i>
            <div class="timeline-item">
              <h3 class="timeline-header">Início de Projeto</h3>
              <div class="timeline-body"> 
                <span class="text-light-blue"><%= project.name %></span> começa nesse dia!
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
      <% @projects_end.each do |project| %>
        <% if project.end_date.month == date.month && project.end_date.day == date.day %>
          <li class="time-label">
            <span class="bg-gray">
              <%= date.strftime("%d %b %y") %>
            </span>
          </li>
          <li>
            <i class="fa fa-check bg-navy"></i>
            <div class="timeline-item">
              <h3 class="timeline-header">Fim de Projeto</h3>
              <div class="timeline-body"> 
                <span class="text-navy"><%= project.name %></span> termina nesse dia!
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
      <% @projects_expected.each do |project| %>
        <% if project.expected_date.month == date.month && project.expected_date.day == date.day %>
          <li class="time-label">
            <span class="bg-gray">
              <%= date.strftime("%d %b %y") %>
            </span>
          </li>
          <li>
            <i class="fa fa-thumbs-o-up bg-aqua"></i>
            <div class="timeline-item">
              <h3 class="timeline-header">Final Esperado</h3>
              <div class="timeline-body"> 
                <span class="text-aqua"><%= project.name %></span> tem data de termino prevista neste dia!
              </div>
            </div>
          </li>
        <% end %>
      <% end %>
    <% end %>
</ul>