config/routes.rb
Rails.application.routes.draw do

  get 'administrative', to: 'administrative#index'
  get 'dashboard', to: 'dashboard#index'
  
  namespace :administrative do
    resources :transfers, except: [:show]
    resources :events
    resources :projects
    resources :users
    post 'projects/:id/user_id=:user_id&act=:act', to: 'projects#edit_contributions'
    post 'events/:id/user_id=:user_id&act=:act', to: 'events#edit_participation'
  end
  
  namespace :dashboard do
    get 'transfers', to: "transfers#index"
    resources :events, only: [:index, :show]
    resources :projects, only: [:index, :show]
    resources :users, only: [:index, :show]
    resources :profile, only: [:edit, :update]
  end
  
  devise_for :admins , controllers: {sessions: 'sign/sessions'}
  devise_for :users,  controllers: {sessions: 'sign/sessions', registrations: 'sign/registrations' }
  
  root 'dashboard#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < DashboardController
  
  def index
  	query = ''
    if(params[:q])
      query = params[:q]
    end
    @events = Event.search(query, params[:page])
  end
  
  def show
    @event = Event.find(params[:id])
    @event_users = @event.users
  end 
end

app/controllers/dashboard/profile_controller.rb
class Dashboard::ProfileController < DashboardController
  before_action :set_user, only: [:edit, :update]
  
  
  def edit
  end
  
  def update
    if @user.update(params_profile)
      redirect_to edit_dashboard_profile_path, notice: "Atualizado"
    else
      render :edit
    end
  end
  
  private
  
    def params_profile
      params.require(:user).permit(:name,:birth_date,:address, :postal_code, :city, :gender, :phone, :photo, :role)
    end
    
  
  
    def set_user
      @user = User.find(current_user.id)
    end
end

app/controllers/dashboard/projects_controller.rb
class Dashboard::ProjectsController < DashboardController
  def index
  	query = ''
    if(params[:q])
      query = params[:q]
    end
    @projects = Project.search(query, params[:page])
  end
  
  def show
    @project = Project.find(params[:id])
    @project_users = @project.users
  end
end

app/controllers/dashboard/transfers_controller.rb
class Dashboard::TransfersController < DashboardController
  def index
  	@transferences = Transfer.order(date: :desc).page(params[:page]).per(5)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < DashboardController
  
  def index
  	query = ''
    if(params[:q])  
      query = params[:q]
    end
    @users = User.search(query, params[:page])
  end
  
  def show 
    @user = User.find(params[:id])
    @user_projects = @user.projects
    @user_events = @user.events
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'
  def index
    month = params[:month]
    if month.nil? or month == ''
      month = Date.today.to_s
    end
    @data = Date.parse(month)
    @dates = (@data.to_date..(@data + 1.month).to_date).map{ |date| date}
    @users = User.find_birth_dates_for( @data.to_date, (@data + 1.month).to_date)
    @events = Event.where(date: @data.to_date..(@data + 1.month).to_date ).order(:date)
    @projects_start = Project.where(start_date:  @data.to_date..(@data + 1.month).to_date ).order(:start_date)
    @projects_end = Project.where(end_date:  @data.to_date..(@data + 1.month).to_date ).order(:end_date)
    @projects_expected = Project.where(expected_date:  @data.to_date..(@data + 1.month).to_date ).order(:expected_date)
  end
end

app/helpers/dashboard/events_helper.rb
module Dashboard::EventsHelper
end

app/helpers/dashboard/projects_helper.rb
module Dashboard::ProjectsHelper
end

app/helpers/dashboard/transfers_helper.rb
module Dashboard::TransfersHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/views/dashboard/profile/edit.html.erb
<% if @user.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
        <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>

    </div>
<% end %>
<%= form_for( @user, url: dashboard_profile_path(@user), :html => { :multipart => true }) do |f|  %>
  <h2>Editando Perfil</h1>
  <div class="row">
    <div class="col-md-3">
      <!-- Profile Image -->
      <div class="box box-primary">
        <div class="box-body box-profile">
          <%= image_tag(@user.photo.thumb.url, :class => "profile-user-img img-responsive img-circle", 
          :style => "margin: 0 auto; width: 100px; padding: 3px;  border: 3px solid #d2d6de;") if @user.photo? %>
          <h3 class="profile-username text-center"><%= @user.name %></h3>
          <p class="text-muted text-center"><%= @user.role %></p>
          <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
              <b>Projetos</b> <a class="pull-right"><%= @user.contributions.count %></a>
            </li>
            <li class="list-group-item">
              <b>Eventos</b> <a class="pull-right"><%= @user.participations.count %></a>
            </li>
          </ul>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <div class="col-md-9">
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Informações</h3>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <div class="form-horizontal">
          <div class="box-body">
            <div class="form-group">
              <%= f.label :name, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :name, class: "form-control", placeholder: "Nome" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :birth_date, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :birth_date, class: "form-control datepicker", value: (l(@user.birth_date) unless @user.birth_date.blank?) %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :address, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :address, class: "form-control", placeholder: "Endereço:" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :postal_code, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :postal_code, class: "form-control", placeholder: "CEP" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :city, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :city, class: "form-control", placeholder: "Cidade" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :gender, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :gender, class: "form-control", placeholder: "Gênero" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :phone, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :phone, class: "form-control", placeholder: "Telefone" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :role, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= f.text_field :role, class: "form-control", placeholder: "Cargo" %>
              </div>
            </div>
            <div class="form-group">
              <%= f.label :photo, class:"col-sm-2 control-label"%>
              <div class="col-sm-10">
                <%= image_tag(@user.photo.thumb.url, :class => "img-responsive") if @user.photo? %>
                <%= f.file_field :photo, value: "#{@user.photo_identifier}" %>
              </div>
            </div>
          </div>
          <!-- /.box-body -->
          <div class="box-footer">
            <%= submit_tag "Salvar", class: "btn btn-default" %>
          </div>
          <!-- /.box-footer -->
        </div>
      </div>
    </div>
  </div>

<% end %>